//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.BookingTrucks = new HashSet<BookingTruck>();
        }
    
        public int client_id { get; set; }
        public string client_firstname { get; set; }
        public string client_lastname { get; set; }
        public string business_name { get; set; }
        public string client_landline { get; set; }
        public string client_cellphone { get; set; }
        public string client_address_street { get; set; }
        public string client_address_number { get; set; }
        public string client_address_area { get; set; }
        public string client_address_areacode { get; set; }
        public string client_city { get; set; }
        public Nullable<int> client_login { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingTruck> BookingTrucks { get; set; }
    }
}
