//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Staff()
        {
            this.BookingTrucks = new HashSet<BookingTruck>();
            this.TruckDrivers = new HashSet<TruckDriver>();
        }
    
        public int staff_id { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string id_number { get; set; }
        public string cellphone_number { get; set; }
        public int street_number { get; set; }
        public string street_name { get; set; }
        public string street_area { get; set; }
        public string address_province { get; set; }
        public string address_city { get; set; }
        public int department_id { get; set; }
        public int licence_code_id { get; set; }
        public int banking_id { get; set; }
        public int login_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingTruck> BookingTrucks { get; set; }
        public virtual DriversLiscenceCode DriversLiscenceCode { get; set; }
        public virtual StaffBankingDetail StaffBankingDetail { get; set; }
        public virtual StaffDepartment StaffDepartment { get; set; }
        public virtual StaffLogin StaffLogin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TruckDriver> TruckDrivers { get; set; }
    }
}
