//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqDatabase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TruckAppEntities1 : DbContext
    {
        public TruckAppEntities1()
            : base("name=TruckAppEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BookingGood> BookingGoods { get; set; }
        public virtual DbSet<BookingTruck> BookingTrucks { get; set; }
        public virtual DbSet<ClientLogin> ClientLogins { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<DriversLiscenceCode> DriversLiscenceCodes { get; set; }
        public virtual DbSet<Staff> Staffs { get; set; }
        public virtual DbSet<StaffBankingDetail> StaffBankingDetails { get; set; }
        public virtual DbSet<StaffDepartment> StaffDepartments { get; set; }
        public virtual DbSet<StaffLogin> StaffLogins { get; set; }
        public virtual DbSet<TruckDriver> TruckDrivers { get; set; }
        public virtual DbSet<TruckMaintenance> TruckMaintenances { get; set; }
        public virtual DbSet<Truck> Trucks { get; set; }
        public virtual DbSet<TruckSleepType> TruckSleepTypes { get; set; }
    }
}
