//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Truck
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Truck()
        {
            this.BookingTrucks = new HashSet<BookingTruck>();
        }
    
        public int truck_id { get; set; }
        public string truck_registration { get; set; }
        public int truck_weight { get; set; }
        public int truck_capacity { get; set; }
        public string truck_type { get; set; }
        public int truck_kilos { get; set; }
        public string body_type_trailer { get; set; }
        public int licence_code_id { get; set; }
        public string mode_type { get; set; }
        public string horse_power { get; set; }
        public int fuel_tank_litre { get; set; }
        public int fuel_usage_kilo { get; set; }
        public int sleeping_type_id { get; set; }
        public int maintenance_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingTruck> BookingTrucks { get; set; }
        public virtual DriversLiscenceCode DriversLiscenceCode { get; set; }
        public virtual TruckMaintenance TruckMaintenance { get; set; }
        public virtual TruckSleepType TruckSleepType { get; set; }
    }
}
